### ISSUE TITLE
plot_wavelet fails if I set add_MTM to TRUE

### ISSUE THREAD

**Issue by japhir** [stratigraphy/WaverideR#3] opened 2023-09-21 14:27 UTC
Hi again! Looks awesome so far!

Only issue I've found so far was that when I naively set `add_MTM` to `TRUE` I got the following warning. I could get it to work by setting `add_MTM_peaks = TRUE`.

```r
col_w |>
  select(depth = my_rmcd, scl_ma) |>
  ## astrochron::linterp(genplot = FALSE) |>  # yay, not needed! :)
  WaverideR::analyze_wavelet(lowerPeriod = .3,
                             upperPeriod = 20,
                             omega_nr = 8, 
                             ## verbose = TRUE
                             ) |>
  WaverideR::plot_wavelet(palette_name = "inferno",
                          siglvl = .95,
                          dev_new = FALSE,
                          add_avg = TRUE,
                          add_MTM = TRUE, # NOT WORKING!
                          # add_MTM_peaks = TRUE
                          )
```
```
#> Error in WaverideR::plot_wavelet(WaverideR::analyze_wavelet(select(col_w,  : 
  object 'MTM_res_1' not found
  ```

**Comment by japhir** [comment] 2023-09-21 14:28
Also the default value of dev_new was surprising to me, none of the ggplot functions ever mess with the dev.

**Comment by japhir** [comment] 2023-09-22 08:18
Hi again,

I have some more feedback but I don't want to bother you with opening a whole bunch of issues for minor things.

There are some inconsistencies in parameter/function naming which had me re-read the docs a few times so far. I.e. sometimes you use camelCase (e.g. `useRaster`) other times snake_case (mostly). 

See the [tidyverse style guide](https://style.tidyverse.org/) for some nice pointers on consistent function/parameter/object naming. I have a strong preference for adhering to this quite strictly because it makes your life in the future easier ;-).

Some examples that were confusing: `lowerPeriod`/`upperPeriod` (camel case), `plot.COI` (period separator, uppercase abbrev), `n.levels` (period separator), `periodlab` (no separator) `add_MTM_peaks`/`add_MTM` (_ separator, uppercase abbrev) vs. `demean_mtm`/`detrend_mtm` (snake case).

**Comment by stratigraphy** [comment] 2023-09-22 09:22
Issue 1:

"add_MTM is set to TRUE I plot fails only when also add_MTM_peaks = TRUE then plot succeeds"

The issue was due to an error in some If statements
This was solved by changing"

the line of code ;
 if (add_MTM_peaks == TRUE) {...}

to ;
 if (add_MTM == TRUE | add_MTM_peaks == TRUE) {...}

and 

the line of code ;
  if (add_MTM_peaks == TRUE  {...}

to ;
 if (add_MTM_peaks == TRUE & is.na(MTM_res_2[1,2]) == FALSE) {...}

I've retested it with the example data and should now be fixed and thus the error: "#> Error in WaverideR::plot_wavelet(WaverideR::analyze_wavelet(select(col_w,  : 
  object 'MTM_res_1' not found"  should be solved

issue 2: 
"with regards to "Also the default value of dev_new was surprising to me, none of the ggplot functions ever mess with the dev. I'm one of those weird ones that doesn't use RStudio, so I may be an exception here to what is desired behaviour ;-). It kept creating new x11() windows every time I called the function.""

Opening a window is not a bug put a deliberate feature. As the WaverideR R package is principally designed for (cyclo)stratigraphers which use the Rstudio platform it is paramount that wavelet plots generated using the  WaverideR R package are properly plotted every time. When using the Rstudio GUI the plot window will sometime produce an error of "image too big" or "margins too large" or simply drop off part of the text of a plot.  The issue is due to the plot_wavelet function wanting to plot too much in a small window. This issue is principally due to the fact that the the plot_wavelet plots a raster image which needs space to be properly plotted.  To make sure that a proper and aesthetically pleasing plot is generated for the user a new window is opened by default.  

issue3:
"There are some inconsistencies in parameter/function naming which had me re-read the docs a few times so far. I.e. sometimes you use camelCase (e.g. useRaster) other times snake_case (mostly)."

This is just a semantic discussion which I will handle later or when immediately demanded to be fixed by CRAN to keep my package in the CRAN repository.  For similar semantic or aesthetic issues please post them in the discussion as it does not merit the opening of an issue. 

Greets,
Michiel

**Closed by stratigraphy** 2023-09-22 09:22 UTC
